Merge upstream
ViennaRSS/MMTabBarView pull request #35
Opened 2022-06-19 12:15 UTC by Eitot

2022-06-19 14:34 UTC, TAKeanice requested changes
See inline comment (weak delegate)

2022-06-19 14:34 UTC, TAKeanice commented on MMTabBarView/MMTabBarView/MMTabBarView.h
> +@property (nullable, strong)   IBOutlet id <MMTabBarViewDelegate> delegate;
This will cause retain cycles

2022-06-19 15:16 UTC, TAKeanice commented on MMTabBarView/MMTabBarView/MMTabBarView.h
> +@property (nullable, strong)   IBOutlet id <MMTabBarViewDelegate> delegate;
https://github.com/ViennaRSS/MMTabBarView/commit/3d911232d37ab221ecf2ce9a06b27fb960f7934b reinserted strong and removed weak from the ivar. Only the declaration survived your merge ;)

2022-12-27 15:11 UTC, barijaona commented
I incorporated changes introduced by this in #37

2022-12-27 15:11 UTC, closed without merging